import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import axios from "axios";
import styled from "styled-components";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  axios
    .get(`https://www.themealdb.com/api/json/v1/1/filter.php?i=chicken_breast`)
    .then((res) => {
      console.log(res.data);
    });
  axios
    .get(`https://www.themealdb.com/api/json/v1/1/lookup.php?i=52772`)
    .then((res) => {
      console.log(res.data);
    });

  // var query = "1lb brisket and fries";
  // axios({
  //   method: "GET",
  //   url: "https://api.api-ninjas.com/v1/nutrition?query=" + query,
  //   headers: { "X-Api-Key": "PN+egjNuV73ERprjvn/T6Q==a3sRvM0NzFqd8Wr4" },
  //   contentType: "application/json",
  //   success: function (res) {
  //     console.log(res.data);
  //   },
  // });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}></main>
    </>
  );
}
